### ISSUE TITLE
Transfer via KCP crashes the server side application. 

### ISSUE THREAD

**Issue by atkdef** [v2ray/v2ray-core#804]
English:
Please read the [instruction](https://github.com/v2ray/v2ray-core/blob/master/.github/SUPPORT.md) and answer the following questions before submitting your issue. Thank you.
Please answer all the questions with enough information. All issues not following this template will be closed immediately.

1) What version of V2Ray are you using (If you deploy different version on server and client, please explicitly point out)?

3.5

2) What's your scenario of using V2Ray? E.g., Watching YouTube videos in Chrome via Socks/VMess proxy.

Debian 9 (server) <=> vmess via KCP <=> Win10 (client) with Proxifier
general browsing

3) What did you see? (Please describe in detail, such as timeout, fake TLS certificate etc)

Server side crashed after a few requests from browser, not specific to any website. 
Switching to TCP from KCP, ceteris paribus, works fine without any problem. 

4) What's your expectation?

5) Please attach your configuration file (**Mask IP addresses before submit this issue**).

    Server configuration:
```javascript
{
  "log" : {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbound": {
    "port": ****,
    "protocol": "vmess",
    "settings": {
      "clients": [
        {
          "id": "****",
          "level": 1,
          "alterId": 64,
          "security": "aes-128-gcm"
        }
      ],
      "detour": {
        "to": "dynamicPort"
      }
    },
    "streamSettings":{
      "network":"kcp",
      "kcpSettings": {
        "mtu": 1350,
        "tti": 20,
        "uplinkCapacity": 100,
        "downlinkCapacity": 100,
        "congestion": false,
        "readBufferSize": 2,
        "writeBufferSize": 2,
        "header": {
          "type": "srtp"
        }
      }
    }
  },
  "inboundDetour":[
    {
      "protocol": "vmess",
      "port": "****-****",
      "tag": "dynamicPort",
      "settings": {
        "default": {
          "level": 1,
          "alterId": 32
        }
      },
      "allocate": {
        "strategy": "random",
        "concurrency": 2,
        "refresh": 1
      },
      "streamSettings":{
        "network":"kcp",
        "kcpSettings": {
          "mtu": 1350,
          "tti": 20,
          "uplinkCapacity": 100,
          "downlinkCapacity": 100,
          "congestion": false,
          "readBufferSize": 2,
          "writeBufferSize": 2,
          "header": {
            "type": "srtp"
          }
        }
      }
    }
  ],
  "outbound": {
    "protocol": "freedom",
    "settings": {}
  },
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "routing": {
    "strategy": "rules",
    "settings": {
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "blocked"
        }
      ]
    }
  }
}
```

    Client configuration:
```javascript
{
  "log": {
    "loglevel": "warning"
  },
  "inbound": {
    "port": ****,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "auth": "noauth",
      "udp": true,
      "ip": "127.0.0.1"
    }
  },
  "outbound": {
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "****",
          "port": ****,
          "users": [
            {
              "id": "****",
              "alterId": 64,
              "security": "aes-128-gcm"
            }
          ]
        }
      ]
    },
    "streamSettings": {
      "network": "kcp",
      "kcpSettings" : {
        "header" : {
          "type" : "srtp"
        },
        "mtu" : 1350,
        "congestion" : false,
        "tti" : 20,
        "uplinkCapacity" : 100,
        "writeBufferSize" : 2,
        "readBufferSize" : 2,
        "downlinkCapacity" : 100
      }
    }
  },
  "outboundDetour": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "direct"
    }
  ],
  "dns": {
    "servers": [
      "8.8.8.8",
      "8.8.4.4",
      "localhost"
    ]
  },
  "routing": {
    "strategy": "rules",
    "settings": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "type": "field",
          "ip": [
            "0.0.0.0/8",
            "10.0.0.0/8",
            "100.64.0.0/10",
            "127.0.0.0/8",
            "169.254.0.0/16",
            "172.16.0.0/12",
            "192.0.0.0/24",
            "192.0.2.0/24",
            "192.168.0.0/16",
            "198.18.0.0/15",
            "198.51.100.0/24",
            "203.0.113.0/24",
            "::1/128",
            "fc00::/7",
            "fe80::/10"
          ],
          "outboundTag": "direct"
        }
      ]
    }
  }
}
```

6) Please attach error logs, especially the bottom lines if the file is large. Error log file is usually at `/var/log/v2ray/error.log` on Linux.

    Server error log:
```
panic: runtime error: slice bounds out of range

goroutine 885 [running]:
v2ray.com/core/transport/internet/kcp.(*Connection).Write.func1(0x0, 0x0, 0x0, 0x82e90e, 0xc4207a4000, 0xc42077bdc0)
        src/v2ray.com/core/transport/internet/kcp/connection.go:349 +0xca
v2ray.com/core/common/buf.(*Buffer).Reset(0xc42077bdc0, 0xc42061eb98, 0xc42077bdc0, 0xc42016edc8)
        src/v2ray.com/core/common/buf/buffer.go:79 +0x45
v2ray.com/core/transport/internet/kcp.(*SendingWorker).Push(0xc42077b240, 0xc42061eb98, 0xc42061ec00)
        src/v2ray.com/core/transport/internet/kcp/sending.go:298 +0xbd
v2ray.com/core/transport/internet/kcp.(*Connection).Write(0xc4200f8e00, 0xc420629800, 0x6, 0x800, 0xc4200f8e00, 0xc42061ec01, 0x5b8e6e)
        src/v2ray.com/core/transport/internet/kcp/connection.go:348 +0xb2
v2ray.com/core/common/buf.(*BufferedWriter).Write(0xc4207bc3a0, 0xc420629800, 0x6, 0x800, 0x0, 0x0, 0xc420629800)
        src/v2ray.com/core/common/buf/writer.go:61 +0x2ac
net.(*Buffers).WriteTo(0xc42072f540, 0xbe67a0, 0xc4207bc3a0, 0x800, 0xc420629800, 0x6)
        /usr/local/go/src/net/net.go:639 +0xea
v2ray.com/core/common/crypto.(*CryptionWriter).WriteMultiBuffer(0xc4207bc3c0, 0x0, 0x0, 0x0, 0x0, 0x0)
        src/v2ray.com/core/common/crypto/io.go:60 +0x169
v2ray.com/core/common/crypto.(*AuthenticationWriter).writeStream(0xc42077b480, 0xc51710, 0x0, 0x0, 0x0, 0x0)
        src/v2ray.com/core/common/crypto/auth.go:206 +0x2ee
v2ray.com/core/common/crypto.(*AuthenticationWriter).WriteMultiBuffer(0xc42077b480, 0xc51710, 0x0, 0x0, 0xc42061ee88, 0x1)
        src/v2ray.com/core/common/crypto/auth.go:236 +0x56
v2ray.com/core/proxy/vmess/inbound.transferResponse(0xbe6d20, 0xc420786420, 0xc420712240, 0xc4207bc240, 0xc42043ef78, 0x7fbbf076cb38, 0xc420763320, 0xbe67a0, 0xc4207bc3a0, 0xc42063c400, ...)
        src/v2ray.com/core/proxy/vmess/inbound/inbound.go:173 +0x25a
v2ray.com/core/proxy/vmess/inbound.(*Handler).Process.func2(0x0, 0x0)
        src/v2ray.com/core/proxy/vmess/inbound/inbound.go:250 +0x299
v2ray.com/core/common/signal.executeAndFulfill(0xc4207633e0, 0xc420763440)
        /v2ray/src/v2ray.com/core/common/signal/exec.go:8 +0x27
created by v2ray.com/core/common/signal.ExecuteAsync
        /v2ray/src/v2ray.com/core/common/signal/exec.go:18 +0x67
```
    Client error log:
```
N/A, as the server crashes first. 
```

7) Please attach access log. Access log is usually at '/var/log/v2ray/access.log' on Linux.
```
N/A (for privacy concern), but at a glance there's nothing suspicious.
This piece of information can be provided If it turns out to be important. 
```

Please review your issue before submitting.

8) Other configurations (such as Nginx) and logs.

**Comment by nicholascw** [comment]
Wondering the server's spec, especially memory size. You may also want to monitor your memory usage and adjust your *read/write buffer size* and *congestion* settings based on your performance and targeting i/o speed.

**Comment by atkdef** [comment]
@nicholascw 
I think you're right. Those servers have a very low amount of memory (1GB or less). Given such, is there any workaround to prevent it from crashing?

**Comment by DarienRaymond** [comment]
@atkdef Could you please check if the crash is still reproducible without inboundDetour? i.e., remove 'detour' settings in the main inbound.

**Comment by atkdef** [comment]
@DarienRaymond 
It won't crash if the dynamic port inbound detour is removed. Looks like it can only be reproducible with the combination of this inbound detour and kcp.

**Comment by DarienRaymond** [comment]
One possibility is that kcp crashes when dynamic port refreshes. I am still trying to figure out what went wrong.

**Comment by Balnea** [comment]
Hi, I have a very similar setup as you with v2ray v3.6 and my VPS also hold a memory 1GB. But up to now, I don't have any error logs. The exception in the settings are:
1.   "kcpSettings": {
    "mtu": 1350,
    **"tti": 10,**
    "uplinkCapacity": 100,
    "downlinkCapacity": 100,
    **"congestion": true,**
    **"readBufferSize": 10,**
    **"writeBufferSize": 10,**
    "header": {
      **"type": "utp"**
    }
  }
2.  "allocate": {
      "strategy": "random",
      "concurrency": 2,
      **"refresh": 5**
    },
3. Also the dynamic ports have the same **alterId** number as the first main port, while in your case it is different.
I hope these information could help you.

**Comment by DarienRaymond** [comment]
The crash should have been fixed in 3.8.

**Comment by atkdef** [comment]
Unfortunately, the problem is still reproducible in v3.9. The error log is similar to the previous one. 

'''
panic: runtime error: slice bounds out of range

goroutine 1916 [running]:
v2ray.com/core/transport/internet/kcp.(*Connection).Write.func2(0x0, 0x0, 0x0, 0x91d57e, 0xc421886000, 0xc4218b9800)
        src/v2ray.com/core/transport/internet/kcp/connection.go:357 +0xca
v2ray.com/core/common/buf.(*Buffer).Reset(0xc4218b9800, 0xc4216beb98, 0xc4218b9800, 0xc421302ba0)
        src/v2ray.com/core/common/buf/buffer.go:79 +0x45
v2ray.com/core/transport/internet/kcp.(*SendingWorker).Push(0xc42187e980, 0xc4216beb98, 0xc4216beb00)
        src/v2ray.com/core/transport/internet/kcp/sending.go:298 +0xbd
v2ray.com/core/transport/internet/kcp.(*Connection).Write(0xc420167500, 0xc420815000, 0x6, 0x800, 0x0, 0x0, 0x0)
        src/v2ray.com/core/transport/internet/kcp/connection.go:356 +0x112
v2ray.com/core/common/buf.(*BufferedWriter).Write(0xc4218942a0, 0xc420815000, 0x6, 0x800, 0x0, 0x0, 0xc420815003)
        src/v2ray.com/core/common/buf/writer.go:63 +0x2ac
net.(*Buffers).WriteTo(0xc4211c3320, 0xdbe100, 0xc4218942a0, 0x7fd, 0xc420815003, 0x3)
        /usr/local/go/src/net/net.go:639 +0xea
v2ray.com/core/common/crypto.(*CryptionWriter).WriteMultiBuffer(0xc4218942c0, 0x0, 0x0, 0x0, 0x0, 0x0)
        src/v2ray.com/core/common/crypto/io.go:60 +0x169
v2ray.com/core/common/crypto.(*AuthenticationWriter).writeStream(0xc42187eb80, 0xe39ae8, 0x0, 0x0, 0x0, 0x0)
        src/v2ray.com/core/common/crypto/auth.go:206 +0x2ee
v2ray.com/core/common/crypto.(*AuthenticationWriter).WriteMultiBuffer(0xc42187eb80, 0xe39ae8, 0x0, 0x0, 0xc4216bee88, 0x1)
        src/v2ray.com/core/common/crypto/auth.go:236 +0x56
v2ray.com/core/proxy/vmess/inbound.transferResponse(0xdbe680, 0xc421894240, 0xc420e68cf0, 0xc4218940e0, 0xc420021778, 0x7f315f6abce8, 0xc42175ecc0, 0xdbe100, 0xc4218942a0, 0xc4201c6f60, ...)
        src/v2ray.com/core/proxy/vmess/inbound/inbound.go:209 +0x25a
v2ray.com/core/proxy/vmess/inbound.(*Handler).Process.func2(0x0, 0x0)
        src/v2ray.com/core/proxy/vmess/inbound/inbound.go:281 +0x287
v2ray.com/core/common/signal.executeAndFulfill(0xc420513c00, 0xc42175ede0)
        /v2ray/src/v2ray.com/core/common/signal/exec.go:8 +0x27
created by v2ray.com/core/common/signal.ExecuteAsync
        /v2ray/src/v2ray.com/core/common/signal/exec.go:18 +0x67
'''

It's surprised to see you guys working so hard on this project during the lunar new year. Keep up the good work and finally, happy lunar new year!
